# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_VARIOUSFIELDS = descriptor.Descriptor(
  name='VariousFields',
  full_name='VariousFields',
  filename='test/TestMessages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='req_uint32', full_name='VariousFields.req_uint32', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='opt_uint32', full_name='VariousFields.opt_uint32', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rep_uint32', full_name='VariousFields.rep_uint32', index=2,
      number=3, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_VARIOUSFIELDSLIST = descriptor.Descriptor(
  name='VariousFieldsList',
  full_name='VariousFieldsList',
  filename='test/TestMessages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='fields', full_name='VariousFieldsList.fields', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='field', full_name='VariousFieldsList.field', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_VARIOUSFIELDSLIST.fields_by_name['fields'].message_type = _VARIOUSFIELDS
_VARIOUSFIELDSLIST.fields_by_name['field'].message_type = _VARIOUSFIELDS

class VariousFields(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VARIOUSFIELDS

class VariousFieldsList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VARIOUSFIELDSLIST

